development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: ruby-bbcode_dev
  host: localhost
  username: jack
  password: pass

test:
  # this won't work 
  adapter: postgresql
  encoding: unicode
  database: ruby-bbcode_test
  pool: 5
  host: localhost
  username: jack
  password: pass

production:
  # this won't work 
  adapter: postgresql
  encoding: unicode
  database: ruby-bbcode_production
  pool: 5
  host: localhost
  username: jack
  password: pass
